"""Data pipeline: dataset layout, labels, manifest, OCR training and evaluation.

Layout (repository `data/` folder, override with the KENKEN_DATA environment variable):

    data/
      manifest.json                       index of every sample (generated by `kenken data ingest`)
      primary/                            real data (main evaluation source)
        digital/<N>x<N>/<k>.pdf + .json   kenkenpuzzle.com PDFs        split "dev"
        printed/<N>x<N>/<k>.jpeg + .json  phone photos of printed ones split "test"
      secondary/
        synthetic/<N>x<N>/<k>.jpg + .json generated puzzles             split "synthetic"

Rules
  * raw files are never modified; each sample has a sibling label <k>.json;
  * labels use the API puzzle schema ({"size", "cages"}) plus "meta" and "solution";
  * splits: "dev" may be used to tune/train the OCR, "test" is held out (report numbers),
    "synthetic" is for stress tests.
"""
